// Portable exact serialized donors; generated by retained donor extraction, not role-policy code.
namespace HkPauseContracts;
internal sealed class NativeMapDonors
{
    internal const string ResourceSha256="b3d64dcad88f06a1c4e7f4d0e26ccd1f3f7c02c27e6edd031f23681c304d784d";
    internal const string MetadataSha256="6c2d4b53731caf2939f28f1bd58367d1641590e0b9b28db8bbe399327b54c967";
    internal readonly Dictionary<string,GameObject> Objects=new();
    internal readonly Dictionary<int,Renderer> Renderers=new();
    internal readonly Dictionary<int,TMProOld.TextMeshPro> Labels=new();
    internal readonly Dictionary<int,MeshSortingOrder> Drivers=new();
    internal readonly int[] Art={15103,15772};
    internal readonly int[] Annotations={11817,12599,12611,15106,15111,15605,16376,16277,16517,12422,15780,15109};
    internal NativeMapDonors(HKDualScreen owner)
    {
        owner.mapClone.name="Game_Map";Objects.Add("Game_Map",owner.mapClone);
        AddObject("Game_Map/Ancient Basin","Game_Map","Ancient Basin",false);
        AddObject("Game_Map/City of Tears","Game_Map","City of Tears",false);
        AddObject("Game_Map/Cliffs","Game_Map","Cliffs",false);
        AddObject("Game_Map/Compass Icon","Game_Map","Compass Icon",false);
        AddObject("Game_Map/Crossroads","Game_Map","Crossroads",false);
        AddObject("Game_Map/Crystal Peak","Game_Map","Crystal Peak",false);
        AddObject("Game_Map/Deepnest","Game_Map","Deepnest",false);
        AddObject("Game_Map/Dream_Gate_Pin","Game_Map","Dream_Gate_Pin",false);
        AddObject("Game_Map/Dreamer Pins","Game_Map","Dreamer Pins",false);
        AddObject("Game_Map/Flame Pins","Game_Map","Flame Pins",false);
        AddObject("Game_Map/Fog_Canyon","Game_Map","Fog_Canyon",false);
        AddObject("Game_Map/Fungal Wastes","Game_Map","Fungal Wastes",false);
        AddObject("Game_Map/Green_Path","Game_Map","Green_Path",false);
        AddObject("Game_Map/Kingdoms_Edge","Game_Map","Kingdoms_Edge",false);
        AddObject("Game_Map/Map Markers","Game_Map","Map Markers",true);
        AddObject("Game_Map/Queens_Gardens","Game_Map","Queens_Gardens",false);
        AddObject("Game_Map/Resting_Grounds","Game_Map","Resting_Grounds",false);
        AddObject("Game_Map/Shade Pos","Game_Map","Shade Pos",false);
        AddObject("Game_Map/Town_Tutorial","Game_Map","Town_Tutorial",false);
        AddObject("Game_Map/Waterways","Game_Map","Waterways",false);
        AddObject("Game_Map/City of Tears/Ruins2_06","Game_Map/City of Tears","Ruins2_06",false);
        AddObject("Game_Map/Deepnest/Grub Pins","Game_Map/Deepnest","Grub Pins",true);
        AddObject("Game_Map/Dream_Gate_Pin/glow","Game_Map/Dream_Gate_Pin","glow",true);
        AddObject("Game_Map/Dreamer Pins/Pin_Teacher","Game_Map/Dreamer Pins","Pin_Teacher",true);
        AddObject("Game_Map/Flame Pins/Ruins1_28","Game_Map/Flame Pins","Ruins1_28",true);
        AddObject("Game_Map/Fungal Wastes/Fungus2_14","Game_Map/Fungal Wastes","Fungus2_14",false);
        AddObject("Game_Map/Green_Path/Fungus1_34","Game_Map/Green_Path","Fungus1_34",false);
        AddObject("Game_Map/Kingdoms_Edge/Deepnest_East_03","Game_Map/Kingdoms_Edge","Deepnest_East_03",true);
        AddObject("Game_Map/Kingdoms_Edge/Deepnest_East_06","Game_Map/Kingdoms_Edge","Deepnest_East_06",true);
        AddObject("Game_Map/Kingdoms_Edge/Hive_02","Game_Map/Kingdoms_Edge","Hive_02",false);
        AddObject("Game_Map/Map Markers/B1","Game_Map/Map Markers","B1",false);
        AddObject("Game_Map/City of Tears/Ruins2_06/Sub Area Name (1)","Game_Map/City of Tears/Ruins2_06","Sub Area Name (1)",true);
        AddObject("Game_Map/Deepnest/Grub Pins/Deepnest_Spider_Town","Game_Map/Deepnest/Grub Pins","Deepnest_Spider_Town",false);
        AddObject("Game_Map/Fungal Wastes/Fungus2_14/Sub Area Name (3)","Game_Map/Fungal Wastes/Fungus2_14","Sub Area Name (3)",true);
        AddObject("Game_Map/Green_Path/Fungus1_34/Sub Area Name (3)","Game_Map/Green_Path/Fungus1_34","Sub Area Name (3)",true);
        AddObject("Game_Map/Kingdoms_Edge/Deepnest_East_03/Next Area (2)","Game_Map/Kingdoms_Edge/Deepnest_East_03","Next Area (2)",true);
        AddObject("Game_Map/Kingdoms_Edge/Deepnest_East_06/pin_bench","Game_Map/Kingdoms_Edge/Deepnest_East_06","pin_bench",true);
        AddObject("Game_Map/Fungal Wastes/Fungus2_14/Sub Area Name (3)/pop_up_backboard (1)","Game_Map/Fungal Wastes/Fungus2_14/Sub Area Name (3)","pop_up_backboard (1)",true);
        AddObject("Game_Map/Green_Path/Fungus1_34/Sub Area Name (3)/TMP SubMesh [perpetua_tmpro Material + russian_body Atlas]","Game_Map/Green_Path/Fungus1_34/Sub Area Name (3)","TMP SubMesh [perpetua_tmpro Material + russian_body Atlas]",true);
        AddObject("Game_Map/Kingdoms_Edge/Deepnest_East_03/Next Area (2)/Map_Arrow","Game_Map/Kingdoms_Edge/Deepnest_East_03/Next Area (2)","Map_Arrow",true);
        owner.mapGm.compassIcon=Objects["Game_Map/Compass Icon"];
        owner.mapGm.areaAncientBasin=Objects["Game_Map/Ancient Basin"];
        owner.mapGm.areaCity=Objects["Game_Map/City of Tears"];
        owner.mapGm.areaCliffs=Objects["Game_Map/Cliffs"];
        owner.mapGm.areaCrossroads=Objects["Game_Map/Crossroads"];
        owner.mapGm.areaCrystalPeak=Objects["Game_Map/Crystal Peak"];
        owner.mapGm.areaDeepnest=Objects["Game_Map/Deepnest"];
        owner.mapGm.areaFogCanyon=Objects["Game_Map/Fog_Canyon"];
        owner.mapGm.areaFungalWastes=Objects["Game_Map/Fungal Wastes"];
        owner.mapGm.areaGreenpath=Objects["Game_Map/Green_Path"];
        owner.mapGm.areaKingdomsEdge=Objects["Game_Map/Kingdoms_Edge"];
        owner.mapGm.areaQueensGardens=Objects["Game_Map/Queens_Gardens"];
        owner.mapGm.areaRestingGrounds=Objects["Game_Map/Resting_Grounds"];
        owner.mapGm.areaDirtmouth=Objects["Game_Map/Town_Tutorial"];
        owner.mapGm.areaWaterways=Objects["Game_Map/Waterways"];
        owner.mapGm.flamePins=Objects["Game_Map/Flame Pins"];
        owner.mapGm.dreamerPins=Objects["Game_Map/Dreamer Pins"];
        owner.mapGm.shadeMarker=Objects["Game_Map/Shade Pos"];
        owner.mapGm.dreamGateMarker=Objects["Game_Map/Dream_Gate_Pin"];
        // 15103 art raw 81080bf4bfdf2917cb12ad38223eeb59358025fc706276718ebbb0518d5db119
        AddRenderer<SpriteRenderer>(15103,"Game_Map/Kingdoms_Edge/Hive_02",957720295,0,true,2);
        // 15772 art raw b898cd7be21b7e6740adad7b82d7d4982d4198b0a1b85c2b52e528315426289a
        AddRenderer<SpriteRenderer>(15772,"Game_Map/Green_Path/Fungus1_34",957720295,0,true,2);
        // 11817 label raw 570ad885ef885fda2898062cf2353aeb720be12664b134b5cdef6bb110f1bfb7
        AddRenderer<MeshRenderer>(11817,"Game_Map/City of Tears/Ruins2_06/Sub Area Name (1)",957720295,0,true,10,materialFile:4);
        AddLabel(11817);
        AddDriver(11817,"Inventory",0);
        // 12599 label raw 2117349d7752276a7a1bb4379bc1ef02b2730911469684d60bb7f7c6469c0e91
        AddRenderer<MeshRenderer>(12599,"Game_Map/Green_Path/Fungus1_34/Sub Area Name (3)",957720295,0,true,10,materialFile:4);
        AddLabel(12599);
        AddDriver(12599,"Inventory",0);
        // 12611 submesh raw 9dd80ddef25f5d4ba124593bec2fd20df35568ff9d1ec2f68f423f29e5833573
        AddRenderer<MeshRenderer>(12611,"Game_Map/Green_Path/Fungus1_34/Sub Area Name (3)/TMP SubMesh [perpetua_tmpro Material + russian_body Atlas]",629535577,0,true,0,materialFile:0);
        AddSubmesh(12611,12599,false);
        // 15106 pin raw 151e56648dd5c3040fb9fa4ae3d863313daa86492e9bff61a20ac60b6d6ceec3
        AddRenderer<SpriteRenderer>(15106,"Game_Map/Kingdoms_Edge/Deepnest_East_06/pin_bench",957720295,0,true,2);
        // 15111 grub raw 36ae873a5437dc69ba2a0b2613d35fc097f0fc8b0b6b878c107e15c6402f1c33
        AddRenderer<SpriteRenderer>(15111,"Game_Map/Deepnest/Grub Pins/Deepnest_Spider_Town",957720295,0,true,2);
        // 15605 dreamer raw 2ecd38c6540cfeb1c7f94aa79bfff14bf2359bfaa683b39af59463226e26257b
        AddRenderer<SpriteRenderer>(15605,"Game_Map/Dreamer Pins/Pin_Teacher",957720295,0,true,2);
        // 16376 flame raw d500ef079d14bfe8594dbee3284ed26fc5a4d8b37268f97417897a7cc55071a4
        AddRenderer<SpriteRenderer>(16376,"Game_Map/Flame Pins/Ruins1_28",957720295,0,false,2);
        // 16277 gate raw 1abb5b117606bb7e66c2cd84f0d493109523f1cff8b69861c3223bd71079f24f
        AddRenderer<SpriteRenderer>(16277,"Game_Map/Dream_Gate_Pin/glow",957720295,0,true,2);
        // 16517 marker raw 70bef6aced18948abc95013e766b0ec4fa3eeafa2be3a4740cc45376fb025d76
        AddRenderer<SpriteRenderer>(16517,"Game_Map/Map Markers/B1",957720295,0,true,2);
        // 12422 compass raw f2617d7fa6613840b4c1331c174f2a0802ac31c2824641db06241efa4c81f8e8
        AddRenderer<MeshRenderer>(12422,"Game_Map/Compass Icon",957720295,0,true,6,materialFile:0);
        // 15780 backboard raw b0cc66f4af584b6d948db36d0fc7a1bfb1d018c52cafbb2386d679929f0af137
        AddRenderer<SpriteRenderer>(15780,"Game_Map/Fungal Wastes/Fungus2_14/Sub Area Name (3)/pop_up_backboard (1)",957720295,0,true,2);
        // 15109 arrow raw f58046fa3833e9d51a89d786718b4d0b5422a560c77547bc457d92d296754be1
        AddRenderer<SpriteRenderer>(15109,"Game_Map/Kingdoms_Edge/Deepnest_East_03/Next Area (2)/Map_Arrow",957720295,0,true,2);
        owner.mapGm.mapMarkersBlue[0]=Objects["Game_Map/Map Markers/B1"];
        ((SpriteRenderer)Renderers[15103]).color=new(.9852941036224365f,.9109764099121094f,.6013191938400269f,1);
        ((SpriteRenderer)Renderers[15772]).color=new(.8117647171020508f,1,.7647058963775635f,1);
        ((SpriteRenderer)Renderers[15780]).color=new(1,1,1,.5839999914169312f);
        ((SpriteRenderer)Renderers[16277]).color=new(1,1,1,.5659999847412109f);
    }
    readonly Dictionary<(int File,int Path),object> materials=new();
    void AddObject(string path,string parent,string name,bool active)
    { var go=new GameObject(name);go.transform.SetParent(Objects[parent].transform);go.SetActive(active);Objects.Add(path,go); }
    void AddRenderer<T>(int id,string path,int layer,int order,bool enabled,int material,int materialFile=2) where T:Renderer,new()
    {
        var r=Objects[path].AddComponent<T>();r.sortingLayerID=layer;r.sortingOrder=order;r.enabled=enabled;
        object donor=null;var key=(materialFile,material);
        if(material!=0 && !materials.TryGetValue(key,out donor)) materials.Add(key,donor=new object());r.sharedMaterial=donor;Renderers.Add(id,r);
        if(r is SpriteRenderer sprite) sprite.color=new Color(1,1,1,1);
    }
    void AddLabel(int id)
    { var r=Renderers[id];var tmp=new TMProOld.TextMeshPro(r){fontSharedMaterial=r.sharedMaterial,text="native donor"};r.transform.TextComponents.Add(tmp);Labels.Add(id,tmp); }
    void AddDriver(int id,string layer,int order)
    { var r=Renderers[id];var driver=r.gameObject.AddComponent<MeshSortingOrder>();driver.rend=r;driver.layerName=layer;driver.order=order;Drivers.Add(id,driver); }
    void AddSubmesh(int id,int label,bool enabled)
    { var r=Renderers[id];r.transform.TextComponents.Add(new TMProOld.TMP_SubMesh(r){textComponent=Labels[label],enabled=enabled}); }
    internal void NativeSortingTick() { foreach(var driver in Drivers.Values) driver.Update(); }
    internal void TextChanged() { foreach(var label in Labels.Values) label.NativeMeshChanged(); }
    internal Renderer RecreateFallback()
    {
        var old=Renderers[12611];old.transform.SetParent(null);var tmp=Labels[12599];
        var go=new GameObject("recreated native TMP fallback");go.transform.SetParent(tmp.transform);
        var r=go.AddComponent<MeshRenderer>();r.sortingLayerID=tmp.renderer.sortingLayerID;r.sortingOrder=tmp.renderer.sortingOrder;r.sharedMaterial=old.sharedMaterial;
        go.transform.TextComponents.Add(new TMProOld.TMP_SubMesh(r){textComponent=tmp,enabled=true});tmp.NativeMeshChanged();return r;
    }
}
