<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AssemblyName>HollowKnightPatches</AssemblyName>
    <Nullable>disable</Nullable>
    <DefineConstants>UNITY_ANDROID</DefineConstants>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="src/**/*.cs" />
    <Compile Include="../shared-patches/src/**/*.cs" Link="Shared/%(RecursiveDir)%(Filename)%(Extension)" />
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(UnityManaged)/UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(HollowKnightManaged)/Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
